# version: "3.7"
# services:
#   app:
#     container_name: gemapp
#     restart: always
#     build: .
#     ports:
#       - "3000:3000"
#     links:
#       - mongo
#   mongo:
#     container_name: mongo
#     image: mongo
#     volumes:
#       - ./data:/data/db
#     ports:
#       - "27017:27017"
#   admin-mongo:
#     image: adicom/admin-mongo:latest
#     ports:
#       - "8082:8082"
#     environment:
#       - PORT=8082
#       - CONN_NAME=mongo
#       - DB_HOST=mongo
#     links:
#       - mongo